### ISSUE TITLE
Julia binary location in 0.5

### ISSUE THREAD

**Issue by mortenpi** [staticfloat/julia-debian#4]
I noticed that in the Ubuntu 0.5 build (via the [PPA](https://launchpad.net/~staticfloat/+archive/ubuntu/juliareleases)) the Julia binary is now at `/bin/julia`, not in `/usr/bin`. Was this change intentional (introduced in c31a50ab44c7a83c1470580131e7d0c0f371f5ba maybe)? Wouldn't `/usr/bin` be more appropriate for Julia?

Just for context: I happened to notice this since the change broke a few scripts where I happened to have the absolute path to the system binary.

Also, I hope that I am asking/reporting this in the right place. Assuming that I am, should there maybe be a link to this repo on the PPA's Launchpad page?

cc @staticfloat

**Comment by staticfloat** [comment]
Ahh, I was wondering what had changed.  Thank you, @mortenpi you are totally right, we do indeed need to change this.

**Comment by staticfloat** [comment]
This should be fixed, please `sudo apt-get update && sudo apt-get upgrade julia` to make sure.

**Comment by mortenpi** [comment]
I can confirm that `apt-get upgrade` fetched a new Julia which now installed under `/usr/bin` and seems to work perfectly. Thanks!
